### ISSUE TITLE
Example use cases?

### ISSUE THREAD

**Issue by RoyalIcing** [TimisRobert/ash_trans#1]
Hi, got linked to your library, it looks cool. It took a little while to get my head around, I think a concrete example of a use case would help explain what it’s for as I wasn’t sure if it talked to an API or what the functionality was.

The best example I can think of is how Wikipedia is translated into multiple languages by its readers. Or how blogs sometimes allow people to contribute translations of articles.

Have I got that right?

**Comment by TimisRobert** [comment]
Yes, that would be it's use case.

What I want is to make the equivalent of [Cldr Trans](https://hexdocs.pm/ex_cldr_trans/readme.html), but for the Ash framework.
Since Ash does most of the heavy lifting, the extension is quite small actually.

I have added into the get started tutorial a full example using Phoenix, Ash and Cldr, if you have any more questions I will do my best to answer them!

**Comment by WurmPeter** [comment]
Hello @TimisRobert ,

Thanks for the library and that you added a tutorial. Sadly, I still couldn't figure it out completely... 

I think I miss the following: 

- mount/3 function for the form component 
- a liveview that includes the form component
- Routes for that liveview (new and edit actions) 

The show liveview from the end works with ```live "posts/:id", PostLive.Show, :index```

Besides ash, ash_trans, ex_cldr also ex_cldr_locale_display has to be included in mix.exs (and then added to providers in cldr.ex).
